// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4AR1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4BinMC_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4BinRW_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4MC_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4MixedAR1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4OrderedRW_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4RW_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4Smoothing_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4AR1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4AR1_mod, 0},
    {"_rcpp_module_boot_stan_fit4BinMC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BinMC_mod, 0},
    {"_rcpp_module_boot_stan_fit4BinRW_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4BinRW_mod, 0},
    {"_rcpp_module_boot_stan_fit4MC_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4MC_mod, 0},
    {"_rcpp_module_boot_stan_fit4MixedAR1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4MixedAR1_mod, 0},
    {"_rcpp_module_boot_stan_fit4OrderedRW_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4OrderedRW_mod, 0},
    {"_rcpp_module_boot_stan_fit4RW_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4RW_mod, 0},
    {"_rcpp_module_boot_stan_fit4Smoothing_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4Smoothing_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_EczemaPred(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
