// Generated by rstantools.  Do not edit by hand.

/*
    EczemaPred is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    EczemaPred is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with EczemaPred.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_MixedAR1_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_MixedAR1");
    reader.add_event(7, 7, "include", "/include/truncated_normal.stan");
    reader.add_event(7, 0, "start", "/include/truncated_normal.stan");
    reader.add_event(35, 28, "end", "/include/truncated_normal.stan");
    reader.add_event(35, 8, "restart", "model_MixedAR1");
    reader.add_event(38, 11, "include", "/include/data_lgtd_continuous.stan");
    reader.add_event(38, 0, "start", "/include/data_lgtd_continuous.stan");
    reader.add_event(40, 2, "include", "/include/data_lgtd.stan");
    reader.add_event(40, 0, "start", "/include/data_lgtd.stan");
    reader.add_event(51, 11, "end", "/include/data_lgtd.stan");
    reader.add_event(51, 3, "restart", "/include/data_lgtd_continuous.stan");
    reader.add_event(55, 7, "end", "/include/data_lgtd_continuous.stan");
    reader.add_event(55, 12, "restart", "model_MixedAR1");
    reader.add_event(66, 23, "include", "/include/tdata_lgtd.stan");
    reader.add_event(66, 0, "start", "/include/tdata_lgtd.stan");
    reader.add_event(100, 34, "end", "/include/tdata_lgtd.stan");
    reader.add_event(100, 24, "restart", "model_MixedAR1");
    reader.add_event(123, 47, "include", "/include/tparameters_missing.stan");
    reader.add_event(123, 0, "start", "/include/tparameters_missing.stan");
    reader.add_event(137, 14, "end", "/include/tparameters_missing.stan");
    reader.add_event(137, 48, "restart", "model_MixedAR1");
    reader.add_event(188, 97, "end", "model_MixedAR1");
    return reader;
}
template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
truncated_normal_lpdf(const T0__& y,
                          const T1__& M,
                          const T2__& mu,
                          const T3__& sigma, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 17;
        local_scalar_t__ Z(DUMMY_VAR__);
        (void) Z;  // dummy to suppress unused var warning
        stan::math::initialize(Z, DUMMY_VAR__);
        stan::math::fill(Z, DUMMY_VAR__);
        stan::math::assign(Z,(normal_cdf(M, mu, sigma) - normal_cdf(0, mu, sigma)));
        current_statement_begin__ = 18;
        local_scalar_t__ f(DUMMY_VAR__);
        (void) f;  // dummy to suppress unused var warning
        stan::math::initialize(f, DUMMY_VAR__);
        stan::math::fill(f, DUMMY_VAR__);
        stan::math::assign(f,normal_log(y, mu, sigma));
        current_statement_begin__ = 19;
        return stan::math::promote_scalar<fun_return_scalar_t__>((f - stan::math::log(Z)));
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
template <typename T0__, typename T1__, typename T2__, typename T3__>
typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
truncated_normal_lpdf(const T0__& y,
                          const T1__& M,
                          const T2__& mu,
                          const T3__& sigma, std::ostream* pstream__) {
    return truncated_normal_lpdf<false>(y,M,mu,sigma, pstream__);
}
struct truncated_normal_lpdf_functor__ {
    template <bool propto, typename T0__, typename T1__, typename T2__, typename T3__>
        typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__>::type
    operator()(const T0__& y,
                          const T1__& M,
                          const T2__& mu,
                          const T3__& sigma, std::ostream* pstream__) const {
        return truncated_normal_lpdf(y, M, mu, sigma, pstream__);
    }
};
template <typename T0__, typename T1__, typename T2__, class RNG>
typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
truncated_normal_rng(const T0__& M,
                         const T1__& mu,
                         const T2__& sigma, RNG& base_rng__, std::ostream* pstream__) {
    typedef typename boost::math::tools::promote_args<T0__, T1__, T2__>::type local_scalar_t__;
    typedef local_scalar_t__ fun_return_scalar_t__;
    const static bool propto__ = true;
    (void) propto__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
    int current_statement_begin__ = -1;
    try {
        {
        current_statement_begin__ = 30;
        local_scalar_t__ p1(DUMMY_VAR__);
        (void) p1;  // dummy to suppress unused var warning
        stan::math::initialize(p1, DUMMY_VAR__);
        stan::math::fill(p1, DUMMY_VAR__);
        stan::math::assign(p1,normal_cdf(0, mu, sigma));
        current_statement_begin__ = 31;
        local_scalar_t__ p2(DUMMY_VAR__);
        (void) p2;  // dummy to suppress unused var warning
        stan::math::initialize(p2, DUMMY_VAR__);
        stan::math::fill(p2, DUMMY_VAR__);
        stan::math::assign(p2,normal_cdf(M, mu, sigma));
        current_statement_begin__ = 32;
        local_scalar_t__ u(DUMMY_VAR__);
        (void) u;  // dummy to suppress unused var warning
        stan::math::initialize(u, DUMMY_VAR__);
        stan::math::fill(u, DUMMY_VAR__);
        stan::math::assign(u,uniform_rng(p1, p2, base_rng__));
        current_statement_begin__ = 33;
        local_scalar_t__ x(DUMMY_VAR__);
        (void) x;  // dummy to suppress unused var warning
        stan::math::initialize(x, DUMMY_VAR__);
        stan::math::fill(x, DUMMY_VAR__);
        stan::math::assign(x,((sigma * inv_Phi(u)) + mu));
        current_statement_begin__ = 34;
        return stan::math::promote_scalar<fun_return_scalar_t__>(x);
        }
    } catch (const std::exception& e) {
        stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
        // Next line prevents compiler griping about no return
        throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
    }
}
struct truncated_normal_rng_functor__ {
    template <typename T0__, typename T1__, typename T2__, class RNG>
        typename boost::math::tools::promote_args<T0__, T1__, T2__>::type
    operator()(const T0__& M,
                         const T1__& mu,
                         const T2__& sigma, RNG& base_rng__, std::ostream* pstream__) const {
        return truncated_normal_rng(M, mu, sigma, base_rng__, pstream__);
    }
};
#include <stan_meta_header.hpp>
class model_MixedAR1
  : public stan::model::model_base_crtp<model_MixedAR1> {
private:
        int N_obs;
        int N_pt;
        std::vector<int> k_obs;
        std::vector<int> t_obs;
        int N_test;
        std::vector<int> k_test;
        std::vector<int> t_test;
        double M;
        std::vector<double> y_obs;
        std::vector<double> y_test;
        std::vector<double> prior_sigma;
        std::vector<double> prior_mu_logit_alpha;
        std::vector<double> prior_sigma_logit_alpha;
        std::vector<double> prior_mu_inf;
        std::vector<double> prior_sigma_inf;
        int N_mis;
        std::vector<int> t_max;
        int N;
        std::vector<int> id_start;
        std::vector<int> id_end;
        std::vector<int> idx_obs;
        std::vector<int> idx_test;
public:
    model_MixedAR1(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_MixedAR1(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_MixedAR1_namespace::model_MixedAR1";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 43;
            context__.validate_dims("data initialization", "N_obs", "int", context__.to_vec());
            N_obs = int(0);
            vals_i__ = context__.vals_i("N_obs");
            pos__ = 0;
            N_obs = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_obs", N_obs, 0);
            current_statement_begin__ = 44;
            context__.validate_dims("data initialization", "N_pt", "int", context__.to_vec());
            N_pt = int(0);
            vals_i__ = context__.vals_i("N_pt");
            pos__ = 0;
            N_pt = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_pt", N_pt, 0);
            current_statement_begin__ = 46;
            validate_non_negative_index("k_obs", "N_obs", N_obs);
            context__.validate_dims("data initialization", "k_obs", "int", context__.to_vec(N_obs));
            k_obs = std::vector<int>(N_obs, int(0));
            vals_i__ = context__.vals_i("k_obs");
            pos__ = 0;
            size_t k_obs_k_0_max__ = N_obs;
            for (size_t k_0__ = 0; k_0__ < k_obs_k_0_max__; ++k_0__) {
                k_obs[k_0__] = vals_i__[pos__++];
            }
            size_t k_obs_i_0_max__ = N_obs;
            for (size_t i_0__ = 0; i_0__ < k_obs_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "k_obs[i_0__]", k_obs[i_0__], 1);
                check_less_or_equal(function__, "k_obs[i_0__]", k_obs[i_0__], N_pt);
            }
            current_statement_begin__ = 47;
            validate_non_negative_index("t_obs", "N_obs", N_obs);
            context__.validate_dims("data initialization", "t_obs", "int", context__.to_vec(N_obs));
            t_obs = std::vector<int>(N_obs, int(0));
            vals_i__ = context__.vals_i("t_obs");
            pos__ = 0;
            size_t t_obs_k_0_max__ = N_obs;
            for (size_t k_0__ = 0; k_0__ < t_obs_k_0_max__; ++k_0__) {
                t_obs[k_0__] = vals_i__[pos__++];
            }
            size_t t_obs_i_0_max__ = N_obs;
            for (size_t i_0__ = 0; i_0__ < t_obs_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "t_obs[i_0__]", t_obs[i_0__], 1);
            }
            current_statement_begin__ = 49;
            context__.validate_dims("data initialization", "N_test", "int", context__.to_vec());
            N_test = int(0);
            vals_i__ = context__.vals_i("N_test");
            pos__ = 0;
            N_test = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_test", N_test, 0);
            current_statement_begin__ = 50;
            validate_non_negative_index("k_test", "N_test", N_test);
            context__.validate_dims("data initialization", "k_test", "int", context__.to_vec(N_test));
            k_test = std::vector<int>(N_test, int(0));
            vals_i__ = context__.vals_i("k_test");
            pos__ = 0;
            size_t k_test_k_0_max__ = N_test;
            for (size_t k_0__ = 0; k_0__ < k_test_k_0_max__; ++k_0__) {
                k_test[k_0__] = vals_i__[pos__++];
            }
            size_t k_test_i_0_max__ = N_test;
            for (size_t i_0__ = 0; i_0__ < k_test_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "k_test[i_0__]", k_test[i_0__], 1);
                check_less_or_equal(function__, "k_test[i_0__]", k_test[i_0__], N_pt);
            }
            current_statement_begin__ = 51;
            validate_non_negative_index("t_test", "N_test", N_test);
            context__.validate_dims("data initialization", "t_test", "int", context__.to_vec(N_test));
            t_test = std::vector<int>(N_test, int(0));
            vals_i__ = context__.vals_i("t_test");
            pos__ = 0;
            size_t t_test_k_0_max__ = N_test;
            for (size_t k_0__ = 0; k_0__ < t_test_k_0_max__; ++k_0__) {
                t_test[k_0__] = vals_i__[pos__++];
            }
            size_t t_test_i_0_max__ = N_test;
            for (size_t i_0__ = 0; i_0__ < t_test_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "t_test[i_0__]", t_test[i_0__], 1);
            }
            current_statement_begin__ = 53;
            context__.validate_dims("data initialization", "M", "double", context__.to_vec());
            M = double(0);
            vals_r__ = context__.vals_r("M");
            pos__ = 0;
            M = vals_r__[pos__++];
            check_greater_or_equal(function__, "M", M, 0);
            current_statement_begin__ = 54;
            validate_non_negative_index("y_obs", "N_obs", N_obs);
            context__.validate_dims("data initialization", "y_obs", "double", context__.to_vec(N_obs));
            y_obs = std::vector<double>(N_obs, double(0));
            vals_r__ = context__.vals_r("y_obs");
            pos__ = 0;
            size_t y_obs_k_0_max__ = N_obs;
            for (size_t k_0__ = 0; k_0__ < y_obs_k_0_max__; ++k_0__) {
                y_obs[k_0__] = vals_r__[pos__++];
            }
            size_t y_obs_i_0_max__ = N_obs;
            for (size_t i_0__ = 0; i_0__ < y_obs_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "y_obs[i_0__]", y_obs[i_0__], 0);
                check_less_or_equal(function__, "y_obs[i_0__]", y_obs[i_0__], M);
            }
            current_statement_begin__ = 55;
            validate_non_negative_index("y_test", "N_test", N_test);
            context__.validate_dims("data initialization", "y_test", "double", context__.to_vec(N_test));
            y_test = std::vector<double>(N_test, double(0));
            vals_r__ = context__.vals_r("y_test");
            pos__ = 0;
            size_t y_test_k_0_max__ = N_test;
            for (size_t k_0__ = 0; k_0__ < y_test_k_0_max__; ++k_0__) {
                y_test[k_0__] = vals_r__[pos__++];
            }
            size_t y_test_i_0_max__ = N_test;
            for (size_t i_0__ = 0; i_0__ < y_test_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "y_test[i_0__]", y_test[i_0__], 0);
                check_less_or_equal(function__, "y_test[i_0__]", y_test[i_0__], M);
            }
            current_statement_begin__ = 57;
            validate_non_negative_index("prior_sigma", "2", 2);
            context__.validate_dims("data initialization", "prior_sigma", "double", context__.to_vec(2));
            prior_sigma = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("prior_sigma");
            pos__ = 0;
            size_t prior_sigma_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < prior_sigma_k_0_max__; ++k_0__) {
                prior_sigma[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 58;
            validate_non_negative_index("prior_mu_logit_alpha", "2", 2);
            context__.validate_dims("data initialization", "prior_mu_logit_alpha", "double", context__.to_vec(2));
            prior_mu_logit_alpha = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("prior_mu_logit_alpha");
            pos__ = 0;
            size_t prior_mu_logit_alpha_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < prior_mu_logit_alpha_k_0_max__; ++k_0__) {
                prior_mu_logit_alpha[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 59;
            validate_non_negative_index("prior_sigma_logit_alpha", "2", 2);
            context__.validate_dims("data initialization", "prior_sigma_logit_alpha", "double", context__.to_vec(2));
            prior_sigma_logit_alpha = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("prior_sigma_logit_alpha");
            pos__ = 0;
            size_t prior_sigma_logit_alpha_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < prior_sigma_logit_alpha_k_0_max__; ++k_0__) {
                prior_sigma_logit_alpha[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 60;
            validate_non_negative_index("prior_mu_inf", "2", 2);
            context__.validate_dims("data initialization", "prior_mu_inf", "double", context__.to_vec(2));
            prior_mu_inf = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("prior_mu_inf");
            pos__ = 0;
            size_t prior_mu_inf_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < prior_mu_inf_k_0_max__; ++k_0__) {
                prior_mu_inf[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 61;
            validate_non_negative_index("prior_sigma_inf", "2", 2);
            context__.validate_dims("data initialization", "prior_sigma_inf", "double", context__.to_vec(2));
            prior_sigma_inf = std::vector<double>(2, double(0));
            vals_r__ = context__.vals_r("prior_sigma_inf");
            pos__ = 0;
            size_t prior_sigma_inf_k_0_max__ = 2;
            for (size_t k_0__ = 0; k_0__ < prior_sigma_inf_k_0_max__; ++k_0__) {
                prior_sigma_inf[k_0__] = vals_r__[pos__++];
            }
            // initialize transformed data variables
            current_statement_begin__ = 66;
            N_mis = int(0);
            stan::math::fill(N_mis, std::numeric_limits<int>::min());
            current_statement_begin__ = 71;
            validate_non_negative_index("t_max", "N_pt", N_pt);
            t_max = std::vector<int>(N_pt, int(0));
            stan::math::fill(t_max, std::numeric_limits<int>::min());
            stan::math::assign(t_max,rep_array(0, N_pt));
            current_statement_begin__ = 72;
            N = int(0);
            stan::math::fill(N, std::numeric_limits<int>::min());
            current_statement_begin__ = 73;
            validate_non_negative_index("id_start", "N_pt", N_pt);
            id_start = std::vector<int>(N_pt, int(0));
            stan::math::fill(id_start, std::numeric_limits<int>::min());
            current_statement_begin__ = 74;
            validate_non_negative_index("id_end", "N_pt", N_pt);
            id_end = std::vector<int>(N_pt, int(0));
            stan::math::fill(id_end, std::numeric_limits<int>::min());
            current_statement_begin__ = 75;
            validate_non_negative_index("idx_obs", "N_obs", N_obs);
            idx_obs = std::vector<int>(N_obs, int(0));
            stan::math::fill(idx_obs, std::numeric_limits<int>::min());
            current_statement_begin__ = 76;
            validate_non_negative_index("idx_test", "N_test", N_test);
            idx_test = std::vector<int>(N_test, int(0));
            stan::math::fill(idx_test, std::numeric_limits<int>::min());
            // execute transformed data statements
            current_statement_begin__ = 78;
            for (int i = 1; i <= N_obs; ++i) {
                current_statement_begin__ = 79;
                stan::model::assign(t_max, 
                            stan::model::cons_list(stan::model::index_uni(get_base1(k_obs, i, "k_obs", 1)), stan::model::nil_index_list()), 
                            std::max(get_base1(t_obs, i, "t_obs", 1), get_base1(t_max, get_base1(k_obs, i, "k_obs", 1), "t_max", 1)), 
                            "assigning variable t_max");
            }
            current_statement_begin__ = 81;
            for (int i = 1; i <= N_test; ++i) {
                current_statement_begin__ = 82;
                stan::model::assign(t_max, 
                            stan::model::cons_list(stan::model::index_uni(get_base1(k_test, i, "k_test", 1)), stan::model::nil_index_list()), 
                            std::max(get_base1(t_test, i, "t_test", 1), get_base1(t_max, get_base1(k_test, i, "k_test", 1), "t_max", 1)), 
                            "assigning variable t_max");
            }
            current_statement_begin__ = 84;
            stan::math::assign(N, sum(t_max));
            current_statement_begin__ = 86;
            for (int k = 1; k <= N_pt; ++k) {
                current_statement_begin__ = 87;
                if (as_bool(logical_eq(k, 1))) {
                    current_statement_begin__ = 88;
                    stan::model::assign(id_start, 
                                stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                                1, 
                                "assigning variable id_start");
                } else {
                    current_statement_begin__ = 90;
                    stan::model::assign(id_start, 
                                stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                                (get_base1(id_end, (k - 1), "id_end", 1) + 1), 
                                "assigning variable id_start");
                }
                current_statement_begin__ = 92;
                stan::model::assign(id_end, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            ((get_base1(id_start, k, "id_start", 1) - 1) + get_base1(t_max, k, "t_max", 1)), 
                            "assigning variable id_end");
            }
            current_statement_begin__ = 95;
            for (int i = 1; i <= N_obs; ++i) {
                current_statement_begin__ = 96;
                stan::model::assign(idx_obs, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ((get_base1(id_start, get_base1(k_obs, i, "k_obs", 1), "id_start", 1) - 1) + get_base1(t_obs, i, "t_obs", 1)), 
                            "assigning variable idx_obs");
            }
            current_statement_begin__ = 98;
            for (int i = 1; i <= N_test; ++i) {
                current_statement_begin__ = 99;
                stan::model::assign(idx_test, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            ((get_base1(id_start, get_base1(k_test, i, "k_test", 1), "id_start", 1) - 1) + get_base1(t_test, i, "t_test", 1)), 
                            "assigning variable idx_test");
            }
            current_statement_begin__ = 102;
            stan::math::assign(N_mis, (N - N_obs));
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 106;
            validate_non_negative_index("y_mis", "N_mis", N_mis);
            num_params_r__ += (1 * N_mis);
            current_statement_begin__ = 107;
            num_params_r__ += 1;
            current_statement_begin__ = 110;
            num_params_r__ += 1;
            current_statement_begin__ = 111;
            num_params_r__ += 1;
            current_statement_begin__ = 112;
            validate_non_negative_index("eta_alpha", "N_pt", N_pt);
            num_params_r__ += (1 * N_pt);
            current_statement_begin__ = 115;
            num_params_r__ += 1;
            current_statement_begin__ = 116;
            num_params_r__ += 1;
            current_statement_begin__ = 117;
            validate_non_negative_index("eta_inf", "N_pt", N_pt);
            num_params_r__ += (1 * N_pt);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_MixedAR1() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 106;
        if (!(context__.contains_r("y_mis")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable y_mis missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("y_mis");
        pos__ = 0U;
        validate_non_negative_index("y_mis", "N_mis", N_mis);
        context__.validate_dims("parameter initialization", "y_mis", "double", context__.to_vec(N_mis));
        std::vector<double> y_mis(N_mis, double(0));
        size_t y_mis_k_0_max__ = N_mis;
        for (size_t k_0__ = 0; k_0__ < y_mis_k_0_max__; ++k_0__) {
            y_mis[k_0__] = vals_r__[pos__++];
        }
        size_t y_mis_i_0_max__ = N_mis;
        for (size_t i_0__ = 0; i_0__ < y_mis_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lub_unconstrain(0, M, y_mis[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable y_mis: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 107;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 110;
        if (!(context__.contains_r("mu_logit_alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_logit_alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_logit_alpha");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu_logit_alpha", "double", context__.to_vec());
        double mu_logit_alpha(0);
        mu_logit_alpha = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu_logit_alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_logit_alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 111;
        if (!(context__.contains_r("sigma_logit_alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_logit_alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_logit_alpha");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma_logit_alpha", "double", context__.to_vec());
        double sigma_logit_alpha(0);
        sigma_logit_alpha = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma_logit_alpha);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_logit_alpha: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 112;
        if (!(context__.contains_r("eta_alpha")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable eta_alpha missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("eta_alpha");
        pos__ = 0U;
        validate_non_negative_index("eta_alpha", "N_pt", N_pt);
        context__.validate_dims("parameter initialization", "eta_alpha", "double", context__.to_vec(N_pt));
        std::vector<double> eta_alpha(N_pt, double(0));
        size_t eta_alpha_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_alpha_k_0_max__; ++k_0__) {
            eta_alpha[k_0__] = vals_r__[pos__++];
        }
        size_t eta_alpha_i_0_max__ = N_pt;
        for (size_t i_0__ = 0; i_0__ < eta_alpha_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_unconstrain(eta_alpha[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable eta_alpha: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        current_statement_begin__ = 115;
        if (!(context__.contains_r("mu_inf")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable mu_inf missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("mu_inf");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "mu_inf", "double", context__.to_vec());
        double mu_inf(0);
        mu_inf = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu_inf);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable mu_inf: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 116;
        if (!(context__.contains_r("sigma_inf")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_inf missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_inf");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma_inf", "double", context__.to_vec());
        double sigma_inf(0);
        sigma_inf = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma_inf);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_inf: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 117;
        if (!(context__.contains_r("eta_inf")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable eta_inf missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("eta_inf");
        pos__ = 0U;
        validate_non_negative_index("eta_inf", "N_pt", N_pt);
        context__.validate_dims("parameter initialization", "eta_inf", "double", context__.to_vec(N_pt));
        std::vector<double> eta_inf(N_pt, double(0));
        size_t eta_inf_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_inf_k_0_max__; ++k_0__) {
            eta_inf[k_0__] = vals_r__[pos__++];
        }
        size_t eta_inf_i_0_max__ = N_pt;
        for (size_t i_0__ = 0; i_0__ < eta_inf_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_unconstrain(eta_inf[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable eta_inf: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 106;
            std::vector<local_scalar_t__> y_mis;
            size_t y_mis_d_0_max__ = N_mis;
            y_mis.reserve(y_mis_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < y_mis_d_0_max__; ++d_0__) {
                if (jacobian__)
                    y_mis.push_back(in__.scalar_lub_constrain(0, M, lp__));
                else
                    y_mis.push_back(in__.scalar_lub_constrain(0, M));
            }
            current_statement_begin__ = 107;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 110;
            local_scalar_t__ mu_logit_alpha;
            (void) mu_logit_alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_logit_alpha = in__.scalar_constrain(lp__);
            else
                mu_logit_alpha = in__.scalar_constrain();
            current_statement_begin__ = 111;
            local_scalar_t__ sigma_logit_alpha;
            (void) sigma_logit_alpha;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma_logit_alpha = in__.scalar_lb_constrain(0, lp__);
            else
                sigma_logit_alpha = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 112;
            std::vector<local_scalar_t__> eta_alpha;
            size_t eta_alpha_d_0_max__ = N_pt;
            eta_alpha.reserve(eta_alpha_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < eta_alpha_d_0_max__; ++d_0__) {
                if (jacobian__)
                    eta_alpha.push_back(in__.scalar_constrain(lp__));
                else
                    eta_alpha.push_back(in__.scalar_constrain());
            }
            current_statement_begin__ = 115;
            local_scalar_t__ mu_inf;
            (void) mu_inf;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_inf = in__.scalar_constrain(lp__);
            else
                mu_inf = in__.scalar_constrain();
            current_statement_begin__ = 116;
            local_scalar_t__ sigma_inf;
            (void) sigma_inf;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma_inf = in__.scalar_lb_constrain(0, lp__);
            else
                sigma_inf = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 117;
            std::vector<local_scalar_t__> eta_inf;
            size_t eta_inf_d_0_max__ = N_pt;
            eta_inf.reserve(eta_inf_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < eta_inf_d_0_max__; ++d_0__) {
                if (jacobian__)
                    eta_inf.push_back(in__.scalar_constrain(lp__));
                else
                    eta_inf.push_back(in__.scalar_constrain());
            }
            // transformed parameters
            current_statement_begin__ = 121;
            validate_non_negative_index("alpha", "N_pt", N_pt);
            std::vector<local_scalar_t__> alpha(N_pt, local_scalar_t__(0));
            stan::math::initialize(alpha, DUMMY_VAR__);
            stan::math::fill(alpha, DUMMY_VAR__);
            current_statement_begin__ = 122;
            validate_non_negative_index("y_inf", "N_pt", N_pt);
            std::vector<local_scalar_t__> y_inf(N_pt, local_scalar_t__(0));
            stan::math::initialize(y_inf, DUMMY_VAR__);
            stan::math::fill(y_inf, DUMMY_VAR__);
            current_statement_begin__ = 123;
            validate_non_negative_index("b", "N_pt", N_pt);
            std::vector<local_scalar_t__> b(N_pt, local_scalar_t__(0));
            stan::math::initialize(b, DUMMY_VAR__);
            stan::math::fill(b, DUMMY_VAR__);
            current_statement_begin__ = 126;
            validate_non_negative_index("y", "N", N);
            std::vector<local_scalar_t__> y(N, local_scalar_t__(0));
            stan::math::initialize(y, DUMMY_VAR__);
            stan::math::fill(y, DUMMY_VAR__);
            stan::math::assign(y,rep_array(-(1.0), N));
            // transformed parameters block statements
            current_statement_begin__ = 128;
            stan::model::assign(y, 
                        stan::model::cons_list(stan::model::index_multi(idx_obs), stan::model::nil_index_list()), 
                        y_obs, 
                        "assigning variable y");
            {
            current_statement_begin__ = 130;
            int id(0);
            (void) id;  // dummy to suppress unused var warning
            stan::math::fill(id, std::numeric_limits<int>::min());
            stan::math::assign(id,1);
            current_statement_begin__ = 131;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 132;
                if (as_bool(logical_eq(get_base1(y, i, "y", 1), -(1)))) {
                    current_statement_begin__ = 133;
                    stan::model::assign(y, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                get_base1(y_mis, id, "y_mis", 1), 
                                "assigning variable y");
                    current_statement_begin__ = 134;
                    stan::math::assign(id, (id + 1));
                }
            }
            }
            current_statement_begin__ = 139;
            for (int k = 1; k <= N_pt; ++k) {
                current_statement_begin__ = 140;
                stan::model::assign(alpha, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            inv_logit((mu_logit_alpha + (sigma_logit_alpha * get_base1(eta_alpha, k, "eta_alpha", 1)))), 
                            "assigning variable alpha");
                current_statement_begin__ = 141;
                stan::model::assign(y_inf, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            (mu_inf + (sigma_inf * get_base1(eta_inf, k, "eta_inf", 1))), 
                            "assigning variable y_inf");
                current_statement_begin__ = 142;
                stan::model::assign(b, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            (get_base1(y_inf, k, "y_inf", 1) * (1 - get_base1(alpha, k, "alpha", 1))), 
                            "assigning variable b");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 121;
            size_t alpha_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(alpha[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: alpha" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable alpha: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 122;
            size_t y_inf_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < y_inf_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(y_inf[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: y_inf" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable y_inf: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 123;
            size_t b_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < b_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(b[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: b" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable b: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 126;
            size_t y_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                if (stan::math::is_uninitialized(y[k_0__])) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: y" << "[" << k_0__ << "]";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable y: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            // model body
            current_statement_begin__ = 148;
            lp_accum__.add(std_normal_log<propto__>(eta_alpha));
            current_statement_begin__ = 149;
            lp_accum__.add(std_normal_log<propto__>(eta_inf));
            current_statement_begin__ = 151;
            lp_accum__.add(normal_log<propto__>((sigma / M), get_base1(prior_sigma, 1, "prior_sigma", 1), get_base1(prior_sigma, 2, "prior_sigma", 1)));
            current_statement_begin__ = 152;
            lp_accum__.add(normal_log<propto__>(mu_logit_alpha, get_base1(prior_mu_logit_alpha, 1, "prior_mu_logit_alpha", 1), get_base1(prior_mu_logit_alpha, 2, "prior_mu_logit_alpha", 1)));
            current_statement_begin__ = 153;
            lp_accum__.add(normal_log<propto__>(sigma_logit_alpha, get_base1(prior_sigma_logit_alpha, 1, "prior_sigma_logit_alpha", 1), get_base1(prior_sigma_logit_alpha, 2, "prior_sigma_logit_alpha", 1)));
            current_statement_begin__ = 154;
            lp_accum__.add(normal_log<propto__>((mu_inf / M), get_base1(prior_mu_inf, 1, "prior_mu_inf", 1), get_base1(prior_mu_inf, 2, "prior_mu_inf", 1)));
            current_statement_begin__ = 155;
            lp_accum__.add(normal_log<propto__>((sigma_inf / M), get_base1(prior_sigma_inf, 1, "prior_sigma_inf", 1), get_base1(prior_sigma_inf, 2, "prior_sigma_inf", 1)));
            current_statement_begin__ = 157;
            for (int k = 1; k <= N_pt; ++k) {
                current_statement_begin__ = 159;
                lp_accum__.add(normal_log<propto__>(to_vector(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_min_max((get_base1(id_start, k, "id_start", 1) + 1), get_base1(id_end, k, "id_end", 1)), stan::model::nil_index_list()), "y")), add(multiply(get_base1(alpha, k, "alpha", 1), to_vector(stan::model::rvalue(y, stan::model::cons_list(stan::model::index_min_max(get_base1(id_start, k, "id_start", 1), (get_base1(id_end, k, "id_end", 1) - 1)), stan::model::nil_index_list()), "y"))), get_base1(b, k, "b", 1)), sigma));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("y_mis");
        names__.push_back("sigma");
        names__.push_back("mu_logit_alpha");
        names__.push_back("sigma_logit_alpha");
        names__.push_back("eta_alpha");
        names__.push_back("mu_inf");
        names__.push_back("sigma_inf");
        names__.push_back("eta_inf");
        names__.push_back("alpha");
        names__.push_back("y_inf");
        names__.push_back("b");
        names__.push_back("y");
        names__.push_back("y_rep");
        names__.push_back("lpd");
        names__.push_back("y_pred");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(N_mis);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pt);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pt);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pt);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pt);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pt);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_test);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_test);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_MixedAR1_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        std::vector<double> y_mis;
        size_t y_mis_d_0_max__ = N_mis;
        y_mis.reserve(y_mis_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < y_mis_d_0_max__; ++d_0__) {
            y_mis.push_back(in__.scalar_lub_constrain(0, M));
        }
        size_t y_mis_k_0_max__ = N_mis;
        for (size_t k_0__ = 0; k_0__ < y_mis_k_0_max__; ++k_0__) {
            vars__.push_back(y_mis[k_0__]);
        }
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double mu_logit_alpha = in__.scalar_constrain();
        vars__.push_back(mu_logit_alpha);
        double sigma_logit_alpha = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma_logit_alpha);
        std::vector<double> eta_alpha;
        size_t eta_alpha_d_0_max__ = N_pt;
        eta_alpha.reserve(eta_alpha_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < eta_alpha_d_0_max__; ++d_0__) {
            eta_alpha.push_back(in__.scalar_constrain());
        }
        size_t eta_alpha_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_alpha_k_0_max__; ++k_0__) {
            vars__.push_back(eta_alpha[k_0__]);
        }
        double mu_inf = in__.scalar_constrain();
        vars__.push_back(mu_inf);
        double sigma_inf = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma_inf);
        std::vector<double> eta_inf;
        size_t eta_inf_d_0_max__ = N_pt;
        eta_inf.reserve(eta_inf_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < eta_inf_d_0_max__; ++d_0__) {
            eta_inf.push_back(in__.scalar_constrain());
        }
        size_t eta_inf_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_inf_k_0_max__; ++k_0__) {
            vars__.push_back(eta_inf[k_0__]);
        }
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 121;
            validate_non_negative_index("alpha", "N_pt", N_pt);
            std::vector<double> alpha(N_pt, double(0));
            stan::math::initialize(alpha, DUMMY_VAR__);
            stan::math::fill(alpha, DUMMY_VAR__);
            current_statement_begin__ = 122;
            validate_non_negative_index("y_inf", "N_pt", N_pt);
            std::vector<double> y_inf(N_pt, double(0));
            stan::math::initialize(y_inf, DUMMY_VAR__);
            stan::math::fill(y_inf, DUMMY_VAR__);
            current_statement_begin__ = 123;
            validate_non_negative_index("b", "N_pt", N_pt);
            std::vector<double> b(N_pt, double(0));
            stan::math::initialize(b, DUMMY_VAR__);
            stan::math::fill(b, DUMMY_VAR__);
            current_statement_begin__ = 126;
            validate_non_negative_index("y", "N", N);
            std::vector<double> y(N, double(0));
            stan::math::initialize(y, DUMMY_VAR__);
            stan::math::fill(y, DUMMY_VAR__);
            stan::math::assign(y,rep_array(-(1.0), N));
            // do transformed parameters statements
            current_statement_begin__ = 128;
            stan::model::assign(y, 
                        stan::model::cons_list(stan::model::index_multi(idx_obs), stan::model::nil_index_list()), 
                        y_obs, 
                        "assigning variable y");
            {
            current_statement_begin__ = 130;
            int id(0);
            (void) id;  // dummy to suppress unused var warning
            stan::math::fill(id, std::numeric_limits<int>::min());
            stan::math::assign(id,1);
            current_statement_begin__ = 131;
            for (int i = 1; i <= N; ++i) {
                current_statement_begin__ = 132;
                if (as_bool(logical_eq(get_base1(y, i, "y", 1), -(1)))) {
                    current_statement_begin__ = 133;
                    stan::model::assign(y, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                get_base1(y_mis, id, "y_mis", 1), 
                                "assigning variable y");
                    current_statement_begin__ = 134;
                    stan::math::assign(id, (id + 1));
                }
            }
            }
            current_statement_begin__ = 139;
            for (int k = 1; k <= N_pt; ++k) {
                current_statement_begin__ = 140;
                stan::model::assign(alpha, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            inv_logit((mu_logit_alpha + (sigma_logit_alpha * get_base1(eta_alpha, k, "eta_alpha", 1)))), 
                            "assigning variable alpha");
                current_statement_begin__ = 141;
                stan::model::assign(y_inf, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            (mu_inf + (sigma_inf * get_base1(eta_inf, k, "eta_inf", 1))), 
                            "assigning variable y_inf");
                current_statement_begin__ = 142;
                stan::model::assign(b, 
                            stan::model::cons_list(stan::model::index_uni(k), stan::model::nil_index_list()), 
                            (get_base1(y_inf, k, "y_inf", 1) * (1 - get_base1(alpha, k, "alpha", 1))), 
                            "assigning variable b");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            // write transformed parameters
            if (include_tparams__) {
                size_t alpha_k_0_max__ = N_pt;
                for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                    vars__.push_back(alpha[k_0__]);
                }
                size_t y_inf_k_0_max__ = N_pt;
                for (size_t k_0__ = 0; k_0__ < y_inf_k_0_max__; ++k_0__) {
                    vars__.push_back(y_inf[k_0__]);
                }
                size_t b_k_0_max__ = N_pt;
                for (size_t k_0__ = 0; k_0__ < b_k_0_max__; ++k_0__) {
                    vars__.push_back(b[k_0__]);
                }
                size_t y_k_0_max__ = N;
                for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                    vars__.push_back(y[k_0__]);
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 165;
            validate_non_negative_index("y_rep", "N", N);
            std::vector<double> y_rep(N, double(0));
            stan::math::initialize(y_rep, DUMMY_VAR__);
            stan::math::fill(y_rep, DUMMY_VAR__);
            current_statement_begin__ = 166;
            validate_non_negative_index("lpd", "N_test", N_test);
            std::vector<double> lpd(N_test, double(0));
            stan::math::initialize(lpd, DUMMY_VAR__);
            stan::math::fill(lpd, DUMMY_VAR__);
            current_statement_begin__ = 167;
            validate_non_negative_index("y_pred", "N_test", N_test);
            std::vector<double> y_pred(N_test, double(0));
            stan::math::initialize(y_pred, DUMMY_VAR__);
            stan::math::fill(y_pred, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 169;
            for (int k = 1; k <= N_pt; ++k) {
                current_statement_begin__ = 170;
                stan::model::assign(y_rep, 
                            stan::model::cons_list(stan::model::index_uni(get_base1(id_start, k, "id_start", 1)), stan::model::nil_index_list()), 
                            get_base1(y, get_base1(id_start, k, "id_start", 1), "y", 1), 
                            "assigning variable y_rep");
                current_statement_begin__ = 171;
                for (int t = get_base1(id_start, k, "id_start", 1); t <= (get_base1(id_end, k, "id_end", 1) - 1); ++t) {
                    current_statement_begin__ = 172;
                    stan::model::assign(y_rep, 
                                stan::model::cons_list(stan::model::index_uni((t + 1)), stan::model::nil_index_list()), 
                                truncated_normal_rng(M, ((get_base1(alpha, k, "alpha", 1) * get_base1(y, t, "y", 1)) + get_base1(b, k, "b", 1)), sigma, base_rng__, pstream__), 
                                "assigning variable y_rep");
                }
            }
            current_statement_begin__ = 175;
            stan::math::assign(y_pred, stan::model::rvalue(y_rep, stan::model::cons_list(stan::model::index_multi(idx_test), stan::model::nil_index_list()), "y_rep"));
            current_statement_begin__ = 177;
            for (int i = 1; i <= N_test; ++i) {
                current_statement_begin__ = 178;
                if (as_bool(logical_eq(get_base1(id_start, get_base1(k_test, i, "k_test", 1), "id_start", 1), get_base1(idx_test, i, "idx_test", 1)))) {
                    current_statement_begin__ = 180;
                    stan::model::assign(lpd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                -(stan::math::log(M)), 
                                "assigning variable lpd");
                } else {
                    current_statement_begin__ = 182;
                    stan::model::assign(lpd, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                truncated_normal_lpdf(get_base1(y_test, i, "y_test", 1), M, ((get_base1(alpha, get_base1(k_test, i, "k_test", 1), "alpha", 1) * get_base1(y, (get_base1(idx_test, i, "idx_test", 1) - 1), "y", 1)) + get_base1(b, get_base1(k_test, i, "k_test", 1), "b", 1)), sigma, pstream__), 
                                "assigning variable lpd");
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 165;
            size_t y_rep_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < y_rep_k_0_max__; ++k_0__) {
                vars__.push_back(y_rep[k_0__]);
            }
            current_statement_begin__ = 166;
            size_t lpd_k_0_max__ = N_test;
            for (size_t k_0__ = 0; k_0__ < lpd_k_0_max__; ++k_0__) {
                vars__.push_back(lpd[k_0__]);
            }
            current_statement_begin__ = 167;
            size_t y_pred_k_0_max__ = N_test;
            for (size_t k_0__ = 0; k_0__ < y_pred_k_0_max__; ++k_0__) {
                vars__.push_back(y_pred[k_0__]);
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_MixedAR1";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t y_mis_k_0_max__ = N_mis;
        for (size_t k_0__ = 0; k_0__ < y_mis_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_mis" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_logit_alpha";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_logit_alpha";
        param_names__.push_back(param_name_stream__.str());
        size_t eta_alpha_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_alpha_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta_alpha" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_inf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_inf";
        param_names__.push_back(param_name_stream__.str());
        size_t eta_inf_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_inf_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta_inf" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t alpha_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t y_inf_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < y_inf_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "y_inf" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t b_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < b_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "b" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t y_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "y" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t y_rep_k_0_max__ = N;
        for (size_t k_0__ = 0; k_0__ < y_rep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_rep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lpd_k_0_max__ = N_test;
        for (size_t k_0__ = 0; k_0__ < lpd_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lpd" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t y_pred_k_0_max__ = N_test;
        for (size_t k_0__ = 0; k_0__ < y_pred_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_pred" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t y_mis_k_0_max__ = N_mis;
        for (size_t k_0__ = 0; k_0__ < y_mis_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_mis" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_logit_alpha";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_logit_alpha";
        param_names__.push_back(param_name_stream__.str());
        size_t eta_alpha_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_alpha_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta_alpha" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_inf";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma_inf";
        param_names__.push_back(param_name_stream__.str());
        size_t eta_inf_k_0_max__ = N_pt;
        for (size_t k_0__ = 0; k_0__ < eta_inf_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "eta_inf" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t alpha_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < alpha_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "alpha" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t y_inf_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < y_inf_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "y_inf" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t b_k_0_max__ = N_pt;
            for (size_t k_0__ = 0; k_0__ < b_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "b" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t y_k_0_max__ = N;
            for (size_t k_0__ = 0; k_0__ < y_k_0_max__; ++k_0__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "y" << '.' << k_0__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }
        if (!include_gqs__) return;
        size_t y_rep_k_0_max__ = N;
        for (size_t k_0__ = 0; k_0__ < y_rep_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_rep" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t lpd_k_0_max__ = N_test;
        for (size_t k_0__ = 0; k_0__ < lpd_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "lpd" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t y_pred_k_0_max__ = N_test;
        for (size_t k_0__ = 0; k_0__ < y_pred_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "y_pred" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_MixedAR1_namespace::model_MixedAR1 stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
