name: 'Delete old artifacts'
on:
  schedule:
    - cron: '0 1 1 * *' # every month

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 30days # Setting this to 0 will delete all artifacts
